name: strainify
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - amply=0.1.6
  - annotated-types=0.7.0
  - appdirs=1.4.4
  - argparse-dataclass=2.0.0
  - attrs=25.3.0
  - biopython=1.85
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - capnproto=1.0.2
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.1.8
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - coincbc=2.10.12
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - conda-inject=1.3.2
  - configargparse=1.7
  - connection_pool=0.0.3
  - docutils=0.21.2
  - dpath=2.2.0
  - eido=0.2.4
  - exceptiongroup=1.3.0
  - fastani=1.34
  - fasttree=2.1.11
  - gitdb=4.0.12
  - gitpython=3.1.44
  - gsl=2.7
  - h2=4.2.0
  - harvesttools=1.2
  - hpack=4.1.0
  - htslib=1.22
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - idna=3.10
  - immutables=0.21
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - jinja2=3.1.6
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.14.0
  - libdeflate=1.24
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - llvm-openmp=8.0.1
  - logmuse=0.2.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mash=2.3
  - mdurl=0.1.2
  - nbformat=5.10.4
  - ncurses=6.5
  - numpy=2.2.5
  - openmp=8.0.1
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - parsnp=2.1.4
  - pephubclient=0.4.4
  - peppy=0.40.7
  - perl=5.38.2
  - phipack=1.1
  - pip=25.1.1
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.5
  - platformdirs=4.3.8
  - pluggy=1.5.0
  - psutil=7.0.0
  - pulp=2.8.0
  - pycparser=2.22
  - pydantic=2.11.4
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - pyspoa=0.2.1
  - pytest=8.3.5
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.2
  - raxml=8.2.13
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - reretry=0.11.8
  - rich=14.0.0
  - rpds-py=0.24.0
  - setuptools=80.1.0
  - shellingham=1.5.4
  - six=1.17.0
  - slack-sdk=3.35.0
  - slack_sdk=3.35.0
  - smart_open=7.1.0
  - smmap=5.0.2
  - snakemake=9.3.4
  - snakemake-interface-common=1.17.4
  - snakemake-interface-executor-plugins=9.3.5
  - snakemake-interface-logger-plugins=1.2.3
  - snakemake-interface-report-plugins=1.1.0
  - snakemake-interface-storage-plugins=4.2.1
  - snakemake-minimal=9.3.4
  - tabulate=0.9.0
  - throttler=1.2.2
  - tk=8.6.13
  - tomli=2.2.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.15.4
  - typer-slim=0.15.4
  - typer-slim-standard=0.15.4
  - typing-extensions=4.13.2
  - typing-inspection=0.4.0
  - typing_extensions=4.13.2
  - tzdata=2025b
  - ubiquerg=0.8.0
  - urllib3=2.4.0
  - veracitools=0.1.3
  - wgatools=1.0.0
  - wheel=0.45.1
  - wrapt=1.17.2
  - yaml=0.2.5
  - yte=1.7.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - clarabel==0.10.0
      - cvxpy==1.6.5
      - ecos==2.0.14
      - joblib==1.5.0
      - osqp==1.0.4
      - pysam==0.23.0
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - scs==3.2.7.post2
      - threadpoolctl==3.6.0
