name: strainify
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - attrs=25.3.0=pyh71513ae_0
  - bcftools=1.21=h0a67c2f_1
  - biopython=1.85=py312h01d7ebd_1
  - brotli-python=1.1.0=py312haafddd8_3
  - bwa=0.7.18=h7f84b70_2
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - capnproto=1.0.2=h1c0ecac_3
  - certifi=2025.7.14=py312hecd8cb5_0
  - cffi=1.17.1=py312hf857d28_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - coin-or-cbc=2.10.12=h084678f_4
  - coin-or-cgl=0.60.9=hbb40df2_6
  - coin-or-clp=1.17.10=heb008f4_3
  - coin-or-osi=0.108.11=hd53559c_7
  - coin-or-utils=2.11.12=h1d9b5b1_5
  - coincbc=2.10.12=4_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - dpath=2.2.0=pyha770c72_0
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - fastani=1.34=h84ae2b8_6
  - fasttree=2.1.11=h5c2640d_5
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - gsl=2.7=h93259b0_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harvesttools=1.2=h187553d_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.21=h9f635df_1
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - immutables=0.21=py312h01d7ebd_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h37d8d59_0
  - ld_impl_linux-64=2.43=hf5ec38b_5
  - libblas=3.9.0=31_h7f60823_openblas
  - libcblas=3.9.0=31_hff6cab4_openblas
  - libcurl=8.14.0=h5dec5d8_0
  - libcxx=20.1.8=h3d58e20_1
  - libdeflate=1.24=hcc1b750_0
  - libedit=3.1.20230828=h6c40b1e_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.0=h240833e_0
  - libffi=3.4.6=h281671d_1
  - libgfortran=15.1.0=h5f6db21_0
  - libgfortran5=15.1.0=hfa3c126_0
  - liblapack=3.9.0=31_h236ab99_openblas
  - liblapacke=3.9.0=31_h85686d2_openblas
  - liblzma=5.8.1=hd471939_2
  - libnghttp2=1.64.0=hc7306c3_0
  - libopenblas=0.3.29=openmp_hbf64a52_0
  - libsqlite=3.49.2=hdb6dae5_0
  - libssh2=1.11.1=hed3591d_0
  - libuuid=2.38.1=hb7f2c08_0
  - libxcrypt=4.4.36=h10d778d_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=20.1.8=hf4e0ed4_1
  - logmuse=0.2.8=pyhd8ed1ab_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h3520af0_1
  - mash=2.3=h7460dc2_9
  - mdurl=0.1.2=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - numpy=2.2.5=py312h6693b03_0
  - openssl=3.5.0=hc426f3f_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py312hec45ffd_3
  - parsnp=2.1.4=he136a0b_0
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.7=pyhd8ed1ab_2
  - perl=5.38.2=0_h46256e1_perl5
  - phipack=1.1=h2413b67_6
  - pip=25.1.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - plac=1.4.5=pyhd8ed1ab_0
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - psutil=7.0.0=py312h01d7ebd_0
  - pulp=2.8.0=py312hda2ad9a_2
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.4=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312haba3716_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pysocks=1.7.1=pyha55dd90_7
  - pyspoa=0.2.1=py312he0d4a5b_4
  - pytest=8.3.5=pyhd8ed1ab_0
  - python=3.12.10=h9ccd52b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h3520af0_2
  - raxml=8.2.13=h18d8cf3_3
  - readline=8.2=h7cca4af_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.24.0=py312hb59e30e_0
  - samtools=1.21=ha21ef43_1
  - setuptools=80.1.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - slack-sdk=3.35.0=pyhd8ed1ab_0
  - slack_sdk=3.35.0=hd8ed1ab_0
  - smart_open=7.1.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=9.3.4=hdfd78af_0
  - snakemake-interface-common=1.17.4=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.3.5=pyhdfd78af_0
  - snakemake-interface-logger-plugins=1.2.3=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.1.0=pyhdfd78af_0
  - snakemake-interface-storage-plugins=4.2.1=pyhdfd78af_0
  - snakemake-minimal=9.3.4=pyhdfd78af_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=hf689a15_2
  - tomli=2.2.1=pyhe01879c_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.15.4=pyh9571d03_0
  - typer-slim=0.15.4=pyhe01879c_0
  - typer-slim-standard=0.15.4=haa4fddc_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wgatools=0.1.0=had03b6b_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py312h01d7ebd_0
  - yaml=0.2.5=h4132b18_3
  - yte=1.7.0=pyha770c72_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hd23fc13_2
  - zstandard=0.23.0=py312h01d7ebd_2
  - zstd=1.5.7=h8210216_2
  - pip:
      - clarabel==0.10.0
      - cvxpy==1.6.5
      - ecos==2.0.14
      - joblib==1.5.0
      - osqp==1.0.4
      - pysam==0.23.0
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - scs==3.2.7.post2
      - threadpoolctl==3.6.0
